// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataAdminClient is the client API for DataAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataAdminClient interface {
	FindAdminByEmail(ctx context.Context, in *Admin, opts ...grpc.CallOption) (*Admin, error)
}

type dataAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewDataAdminClient(cc grpc.ClientConnInterface) DataAdminClient {
	return &dataAdminClient{cc}
}

func (c *dataAdminClient) FindAdminByEmail(ctx context.Context, in *Admin, opts ...grpc.CallOption) (*Admin, error) {
	out := new(Admin)
	err := c.cc.Invoke(ctx, "/admin.DataAdmin/FindAdminByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataAdminServer is the server API for DataAdmin service.
// All implementations must embed UnimplementedDataAdminServer
// for forward compatibility
type DataAdminServer interface {
	FindAdminByEmail(context.Context, *Admin) (*Admin, error)
	mustEmbedUnimplementedDataAdminServer()
}

// UnimplementedDataAdminServer must be embedded to have forward compatible implementations.
type UnimplementedDataAdminServer struct {
}

func (UnimplementedDataAdminServer) FindAdminByEmail(context.Context, *Admin) (*Admin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAdminByEmail not implemented")
}
func (UnimplementedDataAdminServer) mustEmbedUnimplementedDataAdminServer() {}

// UnsafeDataAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataAdminServer will
// result in compilation errors.
type UnsafeDataAdminServer interface {
	mustEmbedUnimplementedDataAdminServer()
}

func RegisterDataAdminServer(s grpc.ServiceRegistrar, srv DataAdminServer) {
	s.RegisterService(&DataAdmin_ServiceDesc, srv)
}

func _DataAdmin_FindAdminByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Admin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataAdminServer).FindAdminByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.DataAdmin/FindAdminByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataAdminServer).FindAdminByEmail(ctx, req.(*Admin))
	}
	return interceptor(ctx, in, info, handler)
}

// DataAdmin_ServiceDesc is the grpc.ServiceDesc for DataAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.DataAdmin",
	HandlerType: (*DataAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAdminByEmail",
			Handler:    _DataAdmin_FindAdminByEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Admin/admin.proto",
}
